Proyecto_informatorio/urls.py
from django.contrib      import admin
from django.contrib.auth import views as auth_views
from django.urls         import path
from django.conf.urls    import url, include
from django.conf.urls.static import static
from django.conf import settings
from django.urls.conf import re_path
from django.views.static import serve
# from django.views.generic import TemplateView

from . import views
from apps.blogs.views import CreatePost

urlpatterns = [
    path('admin/', admin.site.urls),
    #vistas basadas en clases
    path('', views.Index.as_view(), name='index'),
    path('services', views.Services.as_view(), name='services'), 
    path('contact', auth_views.LoginView.as_view(template_name = 'pages/contact.html'), name='contact'),
    path('logout', auth_views.logout_then_login, name="logout"), 
    
    path('users/', include('apps.users.urls')),
    path('blogs/', include('apps.blogs.urls')),
   
]
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

apps/blogs/urls.py
"""Posts URLs."""

# Django
from django.urls import path

# Views
from apps.blogs import views

app_name='blogs'

urlpatterns = [
    path('',views.PostsFeedView.as_view(),name='blogs'),
    # path('post/<slug:url>/save_comment',views.save_comment(),name='save_comment'),
    path('post/<slug:url>',views.PostDetailView.as_view(),name='detail'),
    path('create',views.CreatePost.as_view(),name='create'),
]

apps/users/urls.py
from django.urls import path

from . import views

app_name = 'users'

urlpatterns = [
    path('register',views.Registrarme.as_view(),name='register'),
    path('<slug:slug>', views.Profile.as_view(), name='profile'),

    # admin
    # path(),
]

templates/pages/post/create-blog.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}

    <!-- ======= Breadcrumbs ======= -->
    <section id="breadcrumbs" class="breadcrumbs">
        <div class="container">

        <div class="d-flex justify-content-between align-items-center">
            <h2>Creación de un Post</h2>
            <ol>
            <li><a href="{% url 'index' %}">Home</a></li>
            <li><a href="{% url 'blogs:blogs' %}">Blogs</a></li>
            <li></li>
            </ol>
        </div>

        </div>
    </section><!-- End Breadcrumbs -->

    <br/><br/>
    <div class="row">
        <br/><br/><br/>
        <form method="POST" >{% csrf_token %}
            {{ form.as_p }}
            <button>Guardar</button>
        </form>
    </div>
    <br/><br/>
{% endblock body_block%}

templates/pages/post/detail.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}
  
<div class="container">
    <div class="row">
      {% for post in posteos %}
        <div class="col-lg-8">
          <h1 class="mt-4">{{post.title}}</h1>
          <p class="lead">
            por 
            <a href="#">{{post.user.username}}</a>
          </p>
          <hr>
          <p>Escrito el {{post.created}}</p>
          <hr>
          <img class="img-fluid rounded" src="{{ post.image_header.url }}" alt="">
          <hr>
          <p class="lead">{{post.post|safe}}</p>
          <hr>
          {% if user.is_authenticated %}
          <div class="card my-4">
            <h5 class="card-header">Deja un comentario:</h5>
            <div class="card-body">
              <form method="POST" action="{% url 'blogs:save_comment' %}">
                {% csrf_token %}
                <input type="hidden" name="url" value="{{post.url}}" />
                <input type="hidden" name="post" value="{{post.id}}" />
                <div class="form-group">
                  <textarea class="form-control" name="comment" rows="3"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Enviar</button>
              </form>
            </div>
          </div>
          {% endif %}
          {% for comment in comments %}
          <div class="media mb-4">
            {% if comment.user.profile.photo %}
            <img class="d-flex mr-3 rounded-circle" width="50px" height="50px" src="/media/{{ comment.user.profile.photo }}" alt="">
            {% else %}
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
            {% endif %}
            <div class="media-body">
              <h5 class="mt-0">{{comment.user.username}}</h5>
              {{comment.comment}}
            </div>
          </div>
          {% endfor %}
        </div>
      {% endfor %}
{% endblock body_block%}

templates/pages/post/index.html
{% extends 'base.html' %}
{% load static %}

{% block body_block %}

<!-- ======= Breadcrumbs ======= -->
<section id="breadcrumbs" class="breadcrumbs">
  <div class="container">

    <div class="d-flex justify-content-between align-items-center">
      <h2>Blogs</h2>
      <ol>
        <li><a href="{% url 'index' %}">Home</a></li>
        <li><a href="{% url 'blogs:blogs' %}">Blogs</a></li>
      </ol>
    </div>

  </div>
</section><!-- End Breadcrumbs -->

<div class="row">
    <div class="col-md-8">
      <br/><br/><br/><br/>
      <h1 class="my-4">Simple Blog 
      </h1>

      {% for post in posteos %}
      <div class="card mb-4">
        <img class="card-img-top" src="{{post.image_header.url}}">
        
        <div class="card-body">
          <h2 class="card-title">{{post.title}}</h2>
          <p class="card-text">{{post.post|truncatechars:300}}</p>
          <a href="{% url 'blogs:detail' post.url %}" class="btn btn-primary">Leer más &rarr;</a>
        </div>
        <div class="card-footer text-muted">
          Escrito el {{post.created}}
          <a href="{% url 'users:profile' user.username %}">{{post.user.username}}</a>
        </div>
      </div>
      {% endfor %}


      <ul class="pagination justify-content-center mb-4">
        <li class="page-item">
          <a class="page-link" href="#">&larr; Older</a>
        </li>
        <li class="page-item disabled">
          <a class="page-link" href="#">Newer &rarr;</a>
        </li>
      </ul>


    </div>
    {% endblock body_block%}